apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: quarkus-feb24-2
  janus-idp.io/tekton: quarkus-feb24-2
  backstage.io/kubernetes-id: quarkus-feb24-2
  backstage.io/kubernetes-namespace: quarkus-feb24-2
  app.kubernetes.io/part-of: quarkus-feb24-2
resources:
  - application-dev.yaml
