apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: quarkus-feb24-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-feb24-2
  name: quarkus-feb24-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
