apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: quarkus-feb24-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-feb24-2
  name: quarkus-feb24-2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: quarkus-feb24-2
